name: Robot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BASE_URL: https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
  ADMIN_USER: Admin
  ADMIN_PASS: admin123
  HEADLESS: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List project structure
        run: |
          echo "Estrutura atual do projeto:"
          pwd
          ls -R .

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-browser

      - name: Init Robot Framework Browser
        run: |
          rfbrowser init
          npx playwright install-deps
          npx playwright install

      - name: Create reports directory
        run: mkdir -p orangehrm-test/robot/reports

      - name: Run Robot tests
        run: |
          robot \
            --variable BASE_URL:${{ env.BASE_URL }} \
            --variable ADMIN_USER:${{ env.ADMIN_USER }} \
            --variable ADMIN_PASS:${{ env.ADMIN_PASS }} \
            --variable HEADLESS:${{ env.HEADLESS }} \
            -d orangehrm-test/robot/reports \
            orangehrm-test/robot/tests

      - name: Upload Robot reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: orangehrm-test/robot/reports
